let g:floaterm_keymap_toggle = '<Leader>ft'
let g:floaterm_keymap_prev   = '<Leader>fp'
let g:floaterm_keymap_next   = '<Leader>fn'
let g:floaterm_keymap_new = '<Leader>fa'
let g:floaterm_keymap_kill = '<Leader>fk'
